version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: passpass
      MSSQL_PID: Express
    volumes:
      - sqldata:/var/opt/mssql
    restart: unless-stopped

  webapp:
    build: .
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=TaskManagementDB;User Id=sa;Password=passpass;TrustServerCertificate=true"
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "80:8080"
    restart: unless-stopped

volumes:
  sqldata: