services:
  - type: web
    name: taskmanagement-app
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanagement-db
          property: connectionString
    
  - type: pserv  # PostgreSQL database
    name: taskmanagement-db
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile.postgres
    plan: free